/**
 * Meta keywords (EN / RU / UA) — broad discoverability for Google + Yandex.
 */
export const SITE_KEYWORDS: string[] = [
  // Brand
  'Zoobastiks',
  'zoobastiks',
  'Zoobastik',
  'zoobastik',
  'Zubastiks',
  'zubastiks',
  'Zubastik',
  'zubastik',
  'zuobastik',
  'Zoobastiks RGB',
  'zoobastiks minecraft',
  'zoobastik text generator',
  'zoobastik.me',
  'zoobastik me zrgb',
  'zrgb',
  'Зубастик',
  'зубастик',
  'Зубастик генератор',
  'зубастик генератор',
  'Зубастик генератор текста',
  'зубастик генератор текста',
  'Зубастик RGB',
  'зубастик rgb',
  'Зубастик ргб текст',
  'зубастик ргб текст',
  'зубастик майнкрафт',
  'сайт Зубастика',
  'зубастик сайт',
  'Зубастік',
  'зубастік',
  'Zoobastiks генератор',
  'зубастик для майна',
  'зубастикс',
  'зубастикс генератор',
  'зубастик плагины текст',
  // EN core
  'Minecraft RGB',
  'Minecraft RGB generator',
  'Minecraft gradient text',
  'Minecraft rainbow text',
  'Minecraft hex colors',
  'MiniMessage gradient',
  'MiniMessage color',
  'MiniMessage gradient tag',
  'Adventure API text',
  'Minecraft color codes',
  'legacy color codes',
  'ampersand color codes',
  'section sign colors',
  'Minecraft chat formatting',
  'Minecraft plugin text',
  'Minecraft server motd',
  'colored MOTD Minecraft',
  'Minecraft item name color',
  'Minecraft lore color',
  'Minecraft JSON text component',
  'Minecraft BBCode colors',
  'Birdflop style gradient',
  'Birdflop alternative',
  'YAML Minecraft editor',
  'Minecraft enchantment IDs',
  'Minecraft effect IDs',
  'Java Edition commands',
  'Minecraft copy paste colors',
  'LuckPerms message',
  'PlaceholderAPI gradient',
  'DeluxeMenus color',
  'EssentialsX MOTD',
  'mc rgb gen',
  'mc gradient generator',
  'how to rgb text minecraft',
  'colored nick minecraft',
  'minecraft gradient nick',
  'make minecraft chat colorful',
  'mc server colored motd',
  'paper spigot gradient text',
  'velocity mini message color',
  'Minecraft TAB animation',
  'TAB plugin YAML',
  'scoreboard animation Minecraft',
  'header footer TAB',
  'Minecraft unicode symbols',
  'Minecraft nickname symbols',
  'decorative frames Minecraft',
  'online rgb text generator minecraft',
  'free minecraft gradient generator',
  'hex color minecraft java',
  'minecraft bold italic color',
  // RU formal
  'Minecraft RGB генератор',
  'генератор градиента Minecraft',
  'градиент текста Minecraft',
  'радужный текст Minecraft',
  'цветной текст Minecraft',
  'коды цветов Minecraft',
  'MiniMessage градиент',
  'форматирование чата Minecraft',
  'название предмета цвет',
  'описание предмета цвет',
  'плагины Minecraft текст',
  'зачарования Minecraft список ID',
  'таблица зачарований Minecraft',
  'эффекты Minecraft ID',
  'список эффектов Minecraft',
  'YAML Minecraft редактор',
  'редактор YAML плагин',
  'копировать цветной текст',
  'RGB для плагинов',
  'инструмент для цветного текста Minecraft',
  'генератор кодов оформления чата',
  'цветные символы для описания предмета',
  'настройка сообщений сервера Minecraft',
  'текст для hologram плагина',
  'цветной MOTD Minecraft',
  'мотд сервера цветной',
  'генератор MOTD Minecraft',
  'анимация TAB Minecraft',
  'генератор анимации TAB',
  'плагин TAB анимация',
  'символы для ника Minecraft',
  'рамки из символов Minecraft',
  'юникод для MOTD',
  'генератор hex цветов майнкрафт',
  // RU casual
  'ргб генератор майнкрафт',
  'ргб текст майн',
  'ргб ник майнкрафт',
  'как сделать градиент в майне',
  'как покрасить текст в майнкрафте',
  'как цветной текст в чате майн',
  'градиент ника майн',
  'цветной ник генератор',
  'генератор цветного ника',
  'крч ргб текст майн',
  'типа градиент майнкрафт',
  'чат цветной майн сервер',
  'майн ргб копировать',
  'майнкрафт градиент бесплатно',
  'плагин текст цветной онлайн',
  'юзать генератор ргб',
  'залить цветной текст в конфиг',
  'шмот цветное название майн',
  'лор цветной minecraft',
  'мини месседж градиент русский',
  'цветной мотд майн',
  'как сделать цветной мотд',
  'анимка таб майн',
  'символы для таба майн',
  'майнкрафт ргб генератор',
  'майнкрафт градиент текста',
  'gradient text maincraft',
  'mine craft rgb',
  // UA
  'генератор градієнта Minecraft',
  'градієнт тексту Minecraft',
  'кольорові коди Minecraft',
  'форматування чату Minecraft',
  'зачарування Minecraft ID',
  'таблиця зачарувань Minecraft',
  'ефекти Minecraft ID',
  'список ефектів Minecraft',
  'редактор YAML Minecraft',
  'копіювати кольоровий текст',
  'RGB для плагінів',
  'інструмент для кольорового тексту Minecraft',
  'коди кольору для чату сервера',
  'кольоровий MOTD Minecraft',
  'генератор анімацій TAB',
  'символи для ніка Minecraft',
  'рамки з символів Minecraft',
  'як зробити градієнт в майні',
  'кольоровий нік майнкрафт',
  'градієнт тексту для чату',
  'зубастик генератор тексту',
  'зубастик ргб',
  'zoobastiks україна',
  'майн градієнт онлайн',
  'кольоровий текст для плагіна',
  'кольоровий мотд майн',
]

export const TAB_KEYWORDS: string[] = [
  'TAB plugin',
  'TAB animation',
  'Minecraft TAB',
  'TAB texts generator',
  'change-interval',
  'TAB YAML',
  'TAB header animation',
  'TAB footer animation',
  'TAB scoreboard animation',
  'NEAT TAB config',
  'генератор TAB',
  'анимация TAB',
  'плагин TAB',
  'анимация хедера TAB',
  'анимация футера TAB',
  'YAML TAB texts',
  'wave animation TAB',
  'typewriter TAB',
  'glow MiniMessage TAB',
  'генератор анимаций TAB онлайн',
  'таб анимация майнкрафт',
  'анімація TAB',
  'плагін TAB YAML',
  'TAB texts change-interval',
  'цветной TAB Minecraft',
  'градиент в TAB',
  'Zoobastiks TAB',
  'зубастик TAB генератор',
]

export const ENCHANT_KEYWORDS: string[] = [
  'Zoobastiks enchant list',
  'зубастик зачарования',
  'zoobastik enchant id',
  'Minecraft enchantment list',
  'Minecraft enchantment registry id',
  'Java enchantment max level',
  'список зачарований Minecraft',
  'ID зачарований Minecraft',
  'таблица зачарований Minecraft',
  'список зачарувань Minecraft',
  'рівень зачарування max',
  'все зачарования майнкрафт таблица',
  'зачарования для команд копировать',
  'enchant id list java',
  'enchant command ids',
  'minecraft sharpness id',
  'зачарование острота id',
  'зачарування Minecraft Java',
]

export const EFFECTS_KEYWORDS: string[] = [
  'Zoobastiks effects',
  'зубастик эффекты',
  'zoobastik effect id',
  'Minecraft status effect id',
  'Minecraft potion effect command',
  'effect give list',
  'список эффектов Minecraft',
  'ID эффектов Minecraft',
  'ефекти Minecraft список',
  'статус ефекти Minecraft',
  'все эффекты майнкрафт для команды',
  'effect give список id',
  'minecraft speed id',
  'эффекты зелий Minecraft ID',
  'id ефектів Minecraft',
]

export const SYMBOLS_KEYWORDS: string[] = [
  'Minecraft symbols',
  'Minecraft unicode symbols',
  'Minecraft nickname symbols',
  'fancy text minecraft symbols',
  'символы Minecraft',
  'символы для ника Minecraft',
  'юникод символы майнкрафт',
  'символы для MOTD',
  'рамки из символов',
  'декоративные рамки Minecraft',
  'символи Minecraft',
  'символи для ніка',
  'копировать символы Minecraft',
  'символы для TAB',
  'юнікод для мотд',
  'красивые символы майн',
  'цветочные рамки unicode',
  'minecraft fancy nick symbols',
  'символи для ніку майнкрафт',
  'Zoobastiks symbols',
  'зубастик символы',
]

export const SERVER_KEYWORDS: string[] = [
  'minecraft server settings',
  'server.properties editor',
  'paper.yml settings',
  'spigot.yml settings',
  'bukkit.yml settings',
  'minecraft server admin panel',
  'paper-global.yml',
  'paper-world-defaults',
  'настройки сервера minecraft',
  'редактор server.properties',
  'панель администрации майнкрафт',
  'paper global yml',
  'настройка motd server.properties',
  'оптимизация paper сервера',
  'minecraft server config explained',
  'редактор конфігів сервера Minecraft',
  'server.properties пояснення',
  'Zoobastiks server panel',
  'зубастик настройки сервера',
]
